service: sit-753

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1

functions:
  app:
    handler: index.handler
    environment:
      ENV: ${self:provider.stage}
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
